import styles from '../styles/showcase.module.css';
import { MetaFunction } from '@remix-run/node';

export const meta: MetaFunction = () => {
    return [
        { title: "MZCollection | SalesMon" },
        {
            property: "og:title",
            content: "Showcase",
        },
        {
            name: "description",
            content: "Product & App Showcase/Hero",
        },
    ];
};

export default function () {
    return (
        <main className="text-text flex flex-col h-screen py-12 space-y-24">
            <div className="flex flex-row p-8">
                <div className="flex flex-col space-y-4">
                    <h1 className={styles.h1}>What is MZCollection</h1>
                    <p className={styles.p}>MZCollection is a muslimah-wear brand, of a clothes convection.</p>
                </div>
            </div>

            {/* right align */}
            <div className="flex flex-row-reverse p-8">
                <div className="flex flex-col text-right space-y-4">
                    <h1 className={styles.h1}>Sales Monitoring & Analysis Tool</h1>
                    <p className={styles.p}>By integrating your E-Commerce account across all platform, a comprehensive and insightful information are able to be generated by our AI Powered Business Consultant.</p>
                </div>
            </div>

            <div className="flex flex-row p-8">
                <div className="flex flex-col space-y-4">
                    <h1 className={styles.h1}>Not just AI</h1>
                    <p className={styles.p}>The market matters. Using Google Trend's data, we try to provide more view of the market's landscape</p>
                </div>
            </div>

        </main>
    )
}